# Generated by Django 3.1 on 2023-11-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231102_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tblComment',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='tblPost',
            new_name='Post',
        ),
    ]
